name: test

on:
  pull_request:
    branches:
      - '**'
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  ad_hoc_tests_with_Deno:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Download and unzip solutions cache
        uses: ./.github/actions/download_solutions_cache
        with:
          dir: ./public/

      - name: Test GameDecoder
        working-directory: src/gameCode/gameDecoder
        run: deno run --unstable-sloppy-imports --allow-read --allow-env gameDecoder.test.ts

      - name: Test Tnetennums Core
        working-directory: src/gameCode/Tnetennums
        run: deno run --unstable-sloppy-imports --allow-read --allow-env CoreTest.mts

      - name: Test Tnetennums Solver
        working-directory: src/gameCode/Tnetennums
        run: deno run --unstable-sloppy-imports --allow-read --allow-env SolverTest.mts

  test_with_npm:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      # Needs num_of_sols_of_each_grade_and_goal.json & SuperMiniIndexStr.json
      #  Error: src/components/NumbersGame/GameSelector.tsx(29,45): error TS2307: Cannot find module '../../data/num_of_sols_of_each_grade_and_goal.json' or its corresponding type declarations.
      # Error: src/components/NumbersGame/GameSelector.tsx(30,52): error TS2307: Cannot find module '../../data/SuperMiniIndexStr.json'
      - name: Run build
        run: npm run build

      - name: Run Vitest
        run: npm run vitest
      
      # Needs sub_byte latest version, and additional_difficulty
      # - name: Run tests
      #   run: npm run test
